# -*- coding: utf-8 -*-
"""Par ou Ímpar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mWtEZqxu1D8CpALs0BZYnNRg3JgGrJcz
"""

x = int(input('Digite um número:'))
if (x%2)==0:
  print('par')
else:
  print('ímpar')