# -*- coding: utf-8 -*-
"""WebScrapingLivros.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IsJE_Xtm8lOpT6mNkXaJCFvQ0bb5oc3O
"""

from bs4 import BeautifulSoup
import requests
import pandas as pd


url = ('http://books.toscrape.com/')
r = requests.get(url)
soup = BeautifulSoup(r.text, 'html5lib')


textos = soup.find("ol", class_='row')

livros = []
valor = []


titulos = textos.find_all('h3')
for titulo in titulos:
    a_tag = titulo.find('a')
    if a_tag:
        title = a_tag.get('title')
        livros.append(title)


precos = textos.find_all('p', class_='price_color')
for preco in precos:
    p_valor = preco.get_text()

    valor.append(p_valor)


for livro in livros:
    print(livro)

biblioteca={
    'Titulos':livros,
    'Preço':valor
}

df = pd.DataFrame(biblioteca)
df.head(n=20)

