# -*- coding: utf-8 -*-
"""fatorial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LOEeYK0Vsl6RoPYLVFx3BeqSb0z9QXyy
"""

def calcular_fatorial(n):
  if n == 0:
    return 1
  else:
    return n * calcular_fatorial(n-1)
numero = int(input('Digite  o numero natural: '))
fatorial = calcular_fatorial(numero)
print("O fatorial de' , numero é:",fatorial)