# -*- coding: utf-8 -*-
"""Verificandoordenacao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tBIAZTB4B3xbTvCQXYzmLFjXbvUshuc5
"""

p = int(input('Digite o primeiro número: '))
s = int(input('Digite o segundo número: '))
t = int(input('Digite o terceiro número: '))
numeros = [p,s,t]
if numeros == sorted(numeros):
  print("crescente")
else:
  print("não está em ordem crescente")